"""Commit + push of the approved branch only (Part 12). No force, no main."""
from .repository import run_git, DEFAULT_BRANCHES


def commit_fix(repo_path: str, branch: str, incident_id: str, root_cause: str,
               approval_id: str, confidence: float, tests: list) -> str:
    current = run_git(repo_path, ["rev-parse", "--abbrev-ref", "HEAD"])
    if current != branch:
        raise RuntimeError(f"Not on fix branch {branch} (on {current}); refusing to commit")
    if branch.split("/")[-1] in DEFAULT_BRANCHES:
        raise PermissionError("Refusing to commit directly to default branch")
    run_git(repo_path, ["add", "-A"])
    if not run_git(repo_path, ["status", "--porcelain"]):
        raise RuntimeError("Nothing to commit after patch apply")
    title = f"fix(rca): resolve {incident_id} {root_cause}"
    body = (f"Incident: {incident_id}\nRCA: {root_cause}\n"
            f"Patch approval: {approval_id}\nRCA confidence: {confidence}\n"
            f"Tests: {', '.join(tests)}\n\nGenerated by Cloud RCA Agent. Human review required.")
    run_git(repo_path, ["commit", "-m", title, "-m", body])
    return run_git(repo_path, ["rev-parse", "--short", "HEAD"])


def push_branch(repo_path: str, branch: str):
    """Push only the explicit branch ref. Force and bulk pushes are rejected."""
    if branch.split("/")[-1] in DEFAULT_BRANCHES:
        raise PermissionError("Refusing to push default branch")
    return run_git(repo_path, ["push", "origin", f"{branch}:{branch}"])
