"""
GitHub PR creation (Part 13). Never auto-merges. Token never returned/logged.

Uses `gh` CLI when present, else GitHub REST API with GH_TOKEN env.
Without either, returns PR_BLOCKED_NO_TOKEN with the exact command to run.
"""
import json
import os
import shutil
import subprocess
import urllib.request

MASK = "***"


def pr_body(incident_id: str, service: str, root_cause: str, confidence: float,
            evidence: list, changes: list, risk: str, approval_id: str) -> str:
    ev_lines = "\n".join(f"- {e}" for e in evidence[:6]) or "- (see RCA report)"
    ch_lines = "\n".join(f"- {c}" for c in changes) or "- (see diff)"
    return (
        f"Incident:\n{incident_id}\n\nAffected Service:\n{service}\n\n"
        f"Root Cause:\n{root_cause}\n\nRCA Confidence:\n{int(confidence * 100)}%\n\n"
        f"Supporting Evidence:\n{ev_lines}\n\nCode Changes:\n{ch_lines}\n\n"
        f"Risk:\n{risk}\n\nValidation:\n- unit tests passed\n- incident-scenario tests passed\n\n"
        f"Approval:\n{approval_id}\n\nGenerated by:\nCloud RCA Agent\n"
    )


def pr_title(incident_id: str, summary: str) -> str:
    return f"[RCA {incident_id}] {summary}"[:120]


def _gh_available() -> bool:
    return shutil.which("gh") is not None


def create_pr(repo_path: str, branch: str, base: str, title: str, body: str) -> dict:
    """Returns {pr_url, pr_number} or {blocked, hint}. Never merges."""
    if branch.split("/")[-1] in ("main", "master"):
        raise PermissionError("Refusing to open PR from default branch")
    if _gh_available():
        proc = subprocess.run(
            ["gh", "pr", "create", "--repo", _repo_slug(repo_path) or "",
             "--head", branch, "--base", base, "--title", title, "--body", body],
            cwd=repo_path, capture_output=True, text=True, timeout=120)
        # gh prints the PR URL on success
        out = (proc.stdout + proc.stderr).strip()
        if proc.returncode == 0 and "http" in out:
            url = out.split()[-1]
            number = int(url.rstrip("/").split("/")[-1]) if url.rstrip("/").split("/")[-1].isdigit() else None
            return {"pr_url": url, "pr_number": number}
        return {"blocked": "GH_FAILED", "hint": out[-500:]}
    token = os.getenv("GH_TOKEN", "")
    if not token:
        return {"blocked": "PR_BLOCKED_NO_TOKEN",
                "hint": f"Set GH_TOKEN, then run: gh pr create --head {branch} --base {base} --title {title!r}"}
    slug = _repo_slug(repo_path)
    if not slug:
        return {"blocked": "PR_BLOCKED_NO_REMOTE",
                "hint": "No GitHub remote configured on demo repo"}
    req = urllib.request.Request(
        f"https://api.github.com/repos/{slug}/pulls",
        data=json.dumps({"title": title, "head": branch, "base": base,
                         "body": body, "draft": False}).encode(),
        headers={"Authorization": f"Bearer {token}",
                 "Accept": "application/vnd.github+json"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            payload = json.load(resp)
        return {"pr_url": payload.get("html_url"), "pr_number": payload.get("number")}
    except Exception as e:
        return {"blocked": "GH_API_FAILED", "hint": str(e)[:300].replace(token, MASK)}


def _repo_slug(repo_path: str):
    try:
        proc = subprocess.run(["git", "-C", repo_path, "remote", "get-url", "origin"],
                              capture_output=True, text=True, timeout=30)
        url = proc.stdout.strip()
        if "github.com" in url:
            slug = url.split("github.com")[-1].strip(":/").removesuffix(".git")
            if "/" in slug:
                return slug
    except Exception:
        pass
    return os.getenv("DEMO_APP_REPO_SLUG", "")
