"""
Schema for Root Cause Hypotheses.
"""
from typing import List
from pydantic import BaseModel, Field


class RootCauseHypothesis(BaseModel):
    """Candidate root cause hypothesis generated by RCA Hypothesis Agent."""
    hypothesis_id: str = Field(..., description="Unique ID for hypothesis (e.g. HYP-001)")
    root_cause: str = Field(..., description="Proposed explanation of the originating failure")
    root_cause_category: str = Field(..., description="Standardized category of root cause")
    confidence_score: float = Field(..., ge=0.0, le=0.99, description="Initial estimated confidence (< 1.0)")
    supporting_evidence: List[str] = Field(default_factory=list, description="Findings supporting this hypothesis")
    contradictory_evidence: List[str] = Field(default_factory=list, description="Findings that challenge this hypothesis")
    missing_evidence: List[str] = Field(default_factory=list, description="Evidence needed to confirm or disprove")
    affected_services: List[str] = Field(default_factory=list)
    reasoning_summary: str = Field(..., description="Technical rationale linking evidence to root cause")
    suggested_validation_checks: List[str] = Field(default_factory=list)
