"""
Shared Investigation State for Multi-Agent SRE Investigation.
Provides controlled interfaces for reading and updating the state during an investigation.
"""
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone

from schemas.evidence import IncidentEvidence
from schemas.findings import AgentFinding, KnowledgeFinding
from schemas.hypothesis import RootCauseHypothesis
from schemas.validation import HypothesisValidation, ValidationStatus
from schemas.report import BlastRadiusResult, IncidentReport


class AgentExecutionTrace(BaseModel):
    """Observability trace of an individual agent execution."""
    agent_name: str
    started_at: str
    completed_at: str
    tools_invoked: List[str] = Field(default_factory=list)
    duration_ms: float = 0.0
    evidence_items_count: int = 0
    status: str = "COMPLETED"


class InvestigationTrace(BaseModel):
    """Workflow observability trace tracking complete execution audit trail."""
    incident_id: str
    started_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    completed_at: Optional[str] = None
    investigation_rounds: int = 1
    agent_traces: List[AgentExecutionTrace] = Field(default_factory=list)
    hypotheses_generated_count: int = 0
    hypotheses_rejected_count: int = 0
    final_confidence: float = 0.0


class InvestigationState(BaseModel):
    """
    Controlled shared investigation state.
    Specialized agents read context and submit updates through controlled methods.
    """
    incident_id: str
    incident_evidence: IncidentEvidence
    investigation_plan: List[str] = Field(default_factory=list)
    completed_tasks: List[str] = Field(default_factory=list)
    pending_tasks: List[str] = Field(default_factory=list)
    agent_findings: List[AgentFinding] = Field(default_factory=list)
    knowledge_findings: List[KnowledgeFinding] = Field(default_factory=list)
    hypotheses: List[RootCauseHypothesis] = Field(default_factory=list)
    validated_hypotheses: List[HypothesisValidation] = Field(default_factory=list)
    rejected_hypotheses: List[HypothesisValidation] = Field(default_factory=list)
    contradictory_evidence: List[str] = Field(default_factory=list)
    missing_evidence: List[str] = Field(default_factory=list)
    blast_radius: Optional[BlastRadiusResult] = None
    confidence_score: float = 0.0
    investigation_round: int = 1
    max_rounds: int = 3
    investigation_status: str = "IN_PROGRESS"  # IN_PROGRESS, NEEDS_ADDITIONAL_EVIDENCE, COMPLETED, FAILED
    final_report: Optional[IncidentReport] = None
    trace: InvestigationTrace = Field(default_factory=lambda: InvestigationTrace(incident_id="init"))

    def __init__(self, **data):
        super().__init__(**data)
        if self.trace.incident_id == "init":
            self.trace.incident_id = self.incident_id

    # Controlled State Mutation Interfaces

    def set_investigation_plan(self, plan: List[str]):
        """Sets the initial investigation plan generated by the Supervisor Agent."""
        self.investigation_plan = list(plan)
        self.pending_tasks = list(plan)

    def record_task_completion(self, task_name: str):
        """Marks a task as completed."""
        if task_name in self.pending_tasks:
            self.pending_tasks.remove(task_name)
        if task_name not in self.completed_tasks:
            self.completed_tasks.append(task_name)

    def add_agent_finding(self, finding: AgentFinding):
        """Adds a finding produced by a specialized investigation agent."""
        self.agent_findings.append(finding)
        if finding.missing_information:
            for m in finding.missing_information:
                if m not in self.missing_evidence:
                    self.missing_evidence.append(m)

    def add_knowledge_findings(self, findings: List[KnowledgeFinding]):
        """Records grounded runbook and historical incident context."""
        self.knowledge_findings.extend(findings)

    def set_hypotheses(self, hypotheses: List[RootCauseHypothesis]):
        """Sets ranked hypotheses generated by the RCA Hypothesis Agent."""
        self.hypotheses = list(hypotheses)
        self.trace.hypotheses_generated_count += len(hypotheses)

    def add_validation_result(self, validation: HypothesisValidation):
        """Adds a validation verdict produced by the Critic / Validator Agent."""
        if validation.accepted:
            self.validated_hypotheses.append(validation)
        else:
            self.rejected_hypotheses.append(validation)
            self.trace.hypotheses_rejected_count += 1

        for c in validation.contradictions:
            if c not in self.contradictory_evidence:
                self.contradictory_evidence.append(c)

        for mc in validation.missing_checks:
            if mc not in self.missing_evidence:
                self.missing_evidence.append(mc)

    def set_blast_radius(self, blast_radius: BlastRadiusResult):
        """Sets blast radius analysis."""
        self.blast_radius = blast_radius

    def set_final_report(self, report: IncidentReport):
        """Finalizes investigation with completed IncidentReport."""
        self.final_report = report
        self.confidence_score = report.confidence
        self.investigation_status = "COMPLETED"
        self.trace.completed_at = datetime.now(timezone.utc).isoformat()
        self.trace.final_confidence = report.confidence

    def increment_round_with_tasks(self, new_tasks: List[str]) -> bool:
        """
        Increments investigation round if Critic requests more evidence.
        Returns True if round could be incremented, False if max_rounds reached.
        """
        if self.investigation_round >= self.max_rounds:
            self.investigation_status = "MAX_ROUNDS_REACHED"
            return False

        self.investigation_round += 1
        self.trace.investigation_rounds = self.investigation_round
        for t in new_tasks:
            if t not in self.pending_tasks:
                self.pending_tasks.append(t)
        self.investigation_status = "NEEDS_ADDITIONAL_EVIDENCE"
        return True

    def record_agent_trace(self, trace: AgentExecutionTrace):
        """Appends agent execution telemetry for observability."""
        self.trace.agent_traces.append(trace)
